version: "3.9"
services:
  h2:
    image: oscarfonts/h2
    restart: always
    ports:
      - "8082:8082"
    environment:
      - H2_OPTIONS=-ifNotExists
      - H2_DB=book
      - H2_USER=username
      - H2_PASSWORD=password
    volumes:
      - ./h2-data:/opt/h2-data



#java -jar axonserver.jar